Q1. What is the difference between Ordinal Encoding and Label Encoding? Provide an example of when you
might choose one over the other.

In [1]:
# Ordinal encoding is a type of encoding applied to categorical data where the categories have a meaningful order or ranking.
# example : temperature(low,medium,high)
# Label encoding is a more general term that refers to converting categorical data into numerical labels.
# example : categories of flowers

Q2. Explain how Target Guided Ordinal Encoding works and provide an example of when you might use it in
a machine learning project.

In [2]:
# Target Guided Ordinal Encoding is a technique used to encode categorical variables based on the relationship between the 
# categories and the target variable
# when we have large categories in our categorical data then we this method

Q3. Define covariance and explain why it is important in statistical analysis. How is covariance calculated?

In [1]:
# Covariance is a statistical measure that quantifies the degree to which two random variables change together. 
# Covariance is important in statistical analysis for several reasons:
# Relationship Assessment
# Regression Analysis
# Multivariate Analysis
# Covariance between two variables, X and Y, is calculated using the following formula:
# Cov(X,Y)= (∑ i=1 to n (xi - xbar)(yi -ybar) )/n-1

Q4. For a dataset with the following categorical variables: Color (red, green, blue), Size (small, medium,
large), and Material (wood, metal, plastic), perform label encoding using Python's scikit-learn library.
Show your code and explain the output.

In [3]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd
data = {
    'Color': ['red', 'green', 'blue', 'red', 'blue'],
    'Size': ['small', 'medium', 'large', 'small', 'medium'],
    'Material': ['wood', 'metal', 'plastic', 'wood', 'plastic']
}
df = pd.DataFrame(data)

label_encoders = {}
for column in df.columns:
    le = LabelEncoder()
    df[column] = le.fit_transform(df[column])
    label_encoders[column] = le
print("Encoded Dataset:")
print(df)

print("\nLabel Encoders:")
for column, le in label_encoders.items():
    print(f"{column}: {dict(zip(le.classes_, le.transform(le.classes_)))}")


Encoded Dataset:
   Color  Size  Material
0      2     2         2
1      1     1         0
2      0     0         1
3      2     2         2
4      0     1         1

Label Encoders:
Color: {'blue': 0, 'green': 1, 'red': 2}
Size: {'large': 0, 'medium': 1, 'small': 2}
Material: {'metal': 0, 'plastic': 1, 'wood': 2}


Q5. Calculate the covariance matrix for the following variables in a dataset: Age, Income, and Education
level. Interpret the results.

In [4]:
import numpy as np

data = {
    'Age': [25, 30, 35, 28, 40],
    'Income': [50000, 60000, 75000, 55000, 80000],
    'Education': [12, 16, 14, 18, 15]
}

X = np.array([data['Age'], data['Income'], data['Education']])

# Calculate the covariance matrix
covariance_matrix = np.cov(X)

# Display the covariance matrix
print("Covariance Matrix:")
print(covariance_matrix)


Covariance Matrix:
[[3.530e+01 7.575e+04 1.000e+00]
 [7.575e+04 1.675e+08 0.000e+00]
 [1.000e+00 0.000e+00 5.000e+00]]


Q6. You are working on a machine learning project with a dataset containing several categorical
variables, including "Gender" (Male/Female), "Education Level" (High School/Bachelor's/Master's/PhD),
and "Employment Status" (Unemployed/Part-Time/Full-Time). Which encoding method would you use for
each variable, and why?

In [6]:
# Gender (Binary):Binary Encoding or One-Hot Encoding
# Explanation:
#For binary categorical variables like "Gender," you can use binary encoding (0 or 1) or one-hot encoding (creating two binary columns, one for Male and 
# one for Female).
# Education Level (Ordinal):Ordinal Encoding or One-Hot Encoding
# Explanation:
#For ordinal categorical variables like "Education Level," where there is a clear order (High School < Bachelor's < Master's < PhD), you can use ordinal 
# encoding or one-hot encoding.
# Employment Status (Nominal):One-Hot Encoding
# Explanation:
# For nominal categorical variables like "Employment Status," where there is no inherent order, one-hot encoding is commonly used.


Q7. You are analyzing a dataset with two continuous variables, "Temperature" and "Humidity", and two
categorical variables, "Weather Condition" (Sunny/Cloudy/Rainy) and "Wind Direction" (North/South/
East/West). Calculate the covariance between each pair of variables and interpret the results.

In [7]:
import numpy as np
data = {
    'Temperature': [25, 28, 22, 26, 24],
    'Humidity': [50, 60, 45, 55, 48],
}

X = np.array([data['Temperature'], data['Humidity']])

# Calculate the covariance matrix
covariance_matrix = np.cov(X)

# Display the covariance matrix
print("Covariance Matrix:")
print(covariance_matrix)


Covariance Matrix:
[[ 5.  13. ]
 [13.  35.3]]
